spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/didispace/SpringCloud-Learning/
          search-paths: spring_cloud_in_action/config-repo
          username: zheng_yang@suixingpay.com
          password: password
        default-label: master

  application:
    name: config-server
server:
  port: 8888