spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1484419428/springcloud/
          search-paths: tree/master/configserver/src/main/resources
          username: zheng_yang@suixingpay.com
          password: zx158022
        default-label: master

  application:
    name: config-server
server:
  port: 8888